"""first

Revision ID: 67d4f9940df9
Revises: 
Create Date: 2023-02-02 21:27:52.152139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d4f9940df9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=120), nullable=True),
    sa.Column('date_exchange', sa.String(length=120), nullable=True),
    sa.Column('buy_rate', sa.Float(), nullable=True),
    sa.Column('sale_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('my_currency')
    # ### end Alembic commands ###
